# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-29 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asyncactionreport',
            name='system_call',
            field=models.BooleanField(default=False),
        ),
    ]
